export const productList = [
  {
    id: "ELS65L",
    name: "ELS65L CROSS TRAINER",
    model: "ELG56L",
    price: 124879,
    mrp: 139999,
    feature: [
      "WARRANTY :36 MONTHS",
      "LED DISPLAY",
      "SELF GENERATOR SYSTEM",
      "FLY WHEEL: 20 KG",
    ],
  },
  {
    id: "EB15",
    name: "ADLER EB15",
    model: "E815",
    price: 47420,
    mrp: 52999,
    feature: [
      "WARRANTY :24 MONTHS",
      " Machine floor size -  52 x 25 x 62",
      "8 level Auto Electro Magnetic Resistance Control",
      "Fly Wheel - 6Kgs  ",
      "Hand Held Heart Rate Sensor ",
      "Maximum User Weight - 110 Kgs   ",
      "Machine weight -41Kgs   ",
      "Stride length – 15",
      "Single Window Display - Time, ODO, Distance, Calorie & Pulse  ",
      "Fixed & Movable Handle Bar ",
    ],
  },
  {
    id: "TA300",
    name: "ADLER TA300",
    model: "TA300",
    price: 245480,
    mrp: 52999,
    feature: [
      "WARRANTY :28 MONTHS",
      " Machine Floor Size 82' x 39' x63",
      "3.5 HP / 7.0 HP AC Motor",
      "25 Km/hr. Max. Speed",
      "20 Level Automatic Motorized Incline",
      "63” x 24” Extra Wide Running Area",
      "Maximum User Weight: 200 Kgs.",
      "Machine weight - 196 kgs",
      "Un-Foldable Structure",
      "Heart Rate Measurement",
    ],
  },
  {
    id: "TMA45",
    name: "TMA45 TREADMILL",
    model: "TMA45",
    price: 127410,
    mrp: 52999,
    feature: [
      "WARRANTY :36 MONTHS",
      "5.0 H.P PEAK A.C motor",
      "20.0 Km/hr. Max. Speed",
      "15 Level Auto Incline",
      "60'' x 20'' Extra wide running area",
      "Torque power- 9.362 nm",
      "Maximum User Weight: 140 Kgs.",
      "MP3/USB Player",
      "Foldable Structure",
      "Heart Rate Measurement"
    ],
  },
  {
    id: "SB10",
    name: "ADLER SB10",
    model: "SB10",
    price: 41480,
    mrp: 52999,
    feature: [      
      "WARRANTY :24 MONTHS",
      "Machine Floor Size 48' x 22' x 46'",
      "Fly Wheel - 9 Kgs",
      "3 Pcs. Crank Design",
      "Maximum User Weight - 120Kgs",
      "Machine weight - 34 Kgs",
    ],
  },
  {
    id: "SB35L",
    name: "SB35L SPIN BIKE",
    model: "SB35L",
    price: 42550,
    mrp: 52999,
    feature: [
      "WARRANTY :36 MONTHS",
      "Vertical and Horizontal Seat Adjustment ",
      "20 kgs Fly wheel",
      "Heavy Duty 3Pcs. Crank Design",
      "Machine Weight: 52 Kg"
    ],
  },
  {
    id: "RB30",
    name: "RB30 RECUMBENT BIKE",
    model: "RB30",
    price: 45740,
    mrp: 52999,
    feature: [
      "WARRANTY :24 MONTHS",
      "Machine floor size 60' x 25' x 52'",
      "8 Level Manual Magnetic Resistance Control",
      "Fly Wheel 6 Kgs.",
      "Machine weight-45kgs",
      "Maximum User Weight: 130 Kgs.",
      "Hand Held Heart Rate Sensor",
      "Stride length -12"
    ],
  },
  {
    id: "RBS80",
    name: "RECUMBENT BIKE",
    model: "RBS80",
    price: 45740,
    mrp: 52999,
    feature: [
      "WARRANTY :24 MONTHS",
      "Display: LED",
      "Flywheel: 17 kg",
      "Machine Weight: 86 kg",
      "Machine Size: 69” × 29” × 58”",
      "Maximum User Weight: 150kg",
      "Program: 10 Programs",
      "Display Reading - Speed, Time, Calories,Distance, Watt, Pulse, Rpm",
      "Resistance Level: 25 Levels"
    ],
  },
  {
    id: "AC60",
    name: "AB COASTER",
    model: "AC60",
    price: 45740,
    mrp: 52999,
    feature: [
      "WARRANTY :24 MONTHS",
      "Display: LED",
      "Flywheel: 17 kg",
      "Machine Weight: 86 kg",
      "Machine Size: 69” × 29” × 58”",
      "Maximum User Weight: 150kg",
      "Program: 10 Programs",
      "Display Reading - Speed, Time, Calories,Distance, Watt, Pulse, Rpm",
      "Resistance Level: 25 Levels"
    ],
  },
];
